%dataset
%load from july 1994
lshort=dataset(:,1)-tbil;
emmkt=dataset(:,2)-tbil;
globmacro=dataset(:,3)-tbil;
mngfutures=dataset(:,4)-tbil;
convarb=dataset(:,5)-tbil;
eqmneutral=dataset(:,6)-tbil;
evdriven=dataset(:,7)-tbil;
distrsec=dataset(:,8)-tbil;
fixinarb=dataset(:,9)-tbil;
multi=dataset(:,10)-tbil;
%StIME
%lshort
lm=fitlm(CAPM,lshort);
[~,~,coeff]=hac(lm);
%emmkt
lm=fitlm(CAPM,emmkt);
[~,~,coeff]=hac(lm);
%globmacro
lm=fitlm(CAPM,globmacro);
[~,~,coeff]=hac(lm);
%mngfutures
lm=fitlm(CAPM,mngfutures);
[~,~,coeff]=hac(lm);
%convarb
lm=fitlm(CAPM,convarb);
[~,~,coeff]=hac(lm);
%eqmneutral
lm=fitlm(CAPM,eqmneutral);
[~,~,coeff]=hac(lm);
%evdriven
lm=fitlm(CAPM,evdriven);
[~,~,coeff]=hac(lm);
%distrsec
lm=fitlm(CAPM,distrsec);
[~,~,coeff]=hac(lm);
%fixinarb
lm=fitlm(CAPM,fixinarb);
[~,~,coeff]=hac(lm);
%multi
lm=fitlm(CAPM,multi);
[~,~,coeff]=hac(lm);